name: Codesonar GitHub Demo
on:
  pull_request:
env:
  PROJECT_NAME: ${{ github.event.repository.name }}
jobs:
  analyze:
  # perm required to solve "Resource not accessible by integration" warning when trying to upload SARIF
    permissions: write-all
    runs-on:
    # Debian 12 is my laptop
    #  - Debian12
    # MrHermeling is Marks basement machine
     - MrHermeling
    env:
      CODESONAR: /opt/codesonar/codesonar/bin/codesonar
      # JAVA_HOME needed to execute Kotlin Detekt tool
      JAVA_HOME: /opt/codesonar/win32-fetcher/jdk-11-x86_64-pc-linux-gnu
      JAVAC: /opt/codesonar/win32-fetcher/jdk-11-x86_64-pc-linux-gnu/bin/javac
      JAVA: /opt/codesonar/win32-fetcher/jdk-11-x86_64-pc-linux-gnu/bin/java
      CS_JAVA_SCAN: /opt/codesonar/codesonar/bin/cs-java-scan
      DETEKT: /opt/codesonar/win32-fetcher/detekt-cli/bin/detekt-cli
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASS: "${{ secrets.CSONAR_HUB_PASS }}"
      TRUSTED_CERT: "${{ secrets.TRUSTED_CERT }}"
      HUB_CERT: "${{ secrets.ROB_HUB_CERT }}"
      HUB_KEY: "${{ secrets.ROB_HUB_KEY }}"
      CSONAR_HUB_PWFILE: "codesonar.hub.pwfile"
      #CSONAR_HUB_URL: "https://partnerdemo.codesonar.com"
      CSONAR_HUB_URL: "https://duck.dyndns.org:7340"
      CSPYTHON: /opt/codesonar/codesonar/bin/cspython
      CSO_GITHUB: /opt/codesonar-github
      GITHUB_CAFILE: ".github/github.cert.pem"
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
      
    container:
    # this container includes analysis support for C/C++, Java, Python, JS family, Kotlin
      image: ghcr.io/rdaultongt/csonar_github:toolchain-codesonar8.1p0
      credentials:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}
    timeout-minutes: 360
    steps:
     - uses: actions/checkout@v3
     - name: Create Hub Credential File
       run: |
          echo "$CSONAR_HUB_PASS" > "$CSONAR_HUB_PWFILE"
          echo "$HUB_CERT" > hubCert
          echo "$HUB_KEY" > hubKey
          mkdir /github/home/.csurf
          mkdir /github/home/.csurf/codesonar
          echo "$TRUSTED_CERT" > /github/home/.csurf/codesonar/trusted_certs.pem
    # next line required so we can access the main branch - it wll be called remotes/origin/main
    # - run: git config --global --add safe.directory /__w/CSONAR_GITHUB/CSONAR_GITHUB
    # get the set of source files changed for the branch pushed as env var FILELIST
    # tr needed to put all results from git diff onto one space separated line
    # - run: echo $GITHUB_REF
    # - run: git branch -a
    # - run: git diff --name-only remotes/origin/main $GITHUB_REF | tr '\n' ' '
    # - run: echo "FILELIST=`git diff --name-only remotes/origin/main $GITHUB_REF | grep -v yml | tr '\n' ' ' `" >> $GITHUB_ENV
    # - run: echo FILELIST is $FILELIST
     - name: build C/C++
       run: >
          "$CODESONAR" build
          -auth certificate
          -hubcert hubCert
          -hubkey hubKey
          -project /ROB/"$PROJECT_NAME"
          "$PROJECT_NAME"
          "$CSONAR_HUB_URL"
          gcc -c -I. demo.cpp second.cpp
    # TODO: add Python Analysis
     - name: Build and Analyze Java
       run: |
            "$JAVAC" -cp "JAVA/javax.servlet.jar" JAVA/MyServletDemo.java
            ls
            "$CODESONAR" build -auth certificate -hubcert hubCert -hubKey hubKey -project /ROB/"$PROJECT_NAME" "$PROJECT_NAME" "$CSONAR_HUB_URL" -preset java_security "$CS_JAVA_SCAN" -include-artifacts JAVA/MyServletDemo.class -include-sources "JAVA/*.java" -include-sourceless-artifacts "JAVA/javax.servlet.jar"
     - name: analyze NodeGoat JS sources
       run: |
            cd NODEGOAT
            npm install eslint
            npm install @microsoft/eslint-formatter-sarif
            eslint --no-inline-config -c ./node_modules/@humanwhocodes/object-schema/.eslintrc.js -f @microsoft/eslint-formatter-sarif -o nodegoat.sarif app || true
            cd ..
            "$CODESONAR" build -auth certificate -hubcert hubCert -hubKey hubKey -project /ROB/"$PROJECT_NAME" "$PROJECT_NAME" "$CSONAR_HUB_URL" "$CODESONAR" import_sarif.py NODEGOAT/nodegoat.sarif -analyzer eslint -include-sources "NODEGOAT/app/**/*.js"
     - name: analyze the whole codebase + Kotlin OKHTTP sources
       run: |
           "$DETEKT" -i OKHTTP -r sarif:okhttp.sarif || true 
           "$CODESONAR" analyze -auth certificate -hubcert hubCert -hubKey hubKey -project /ROB/"$PROJECT_NAME" "$PROJECT_NAME" "$CSONAR_HUB_URL" -foreground "$CODESONAR" import_sarif.py okhttp.sarif -analyzer detekt -include-sources "OKHTTP/**/*.kt"
     - name: Pull Analysis Results from CodeSonar Hub
       run: >
          "$CODESONAR" dump_warnings.py
          -o warnings.sarif
          --hub "$CSONAR_HUB_URL"
          -auth certificate
          -hubcert hubCert
          -hubkey hubKey
          --project-file "$PROJECT_NAME"
          --sarif
          --src-root "$GITHUB_WORKSPACE"
          --visible-warnings excludeSourcelessArtifacts
          -t 7200
     - name: Cleanup Credential File
       run: shred -u "$CSONAR_HUB_PWFILE"
     - name: Push Analysis Results to GitHub
       uses: github/codeql-action/upload-sarif@v3
       with:
          sarif_file: warnings.sarif
     - name: Push Summary Report
       if: ${{ github.event.pull_request }}
       run: >
          "$CSPYTHON" "$CSO_GITHUB/sarif_summary.py"
          warnings.sarif
          "$CSONAR_HUB_URL"
          "$PROJECT_NAME"
          | "$CSPYTHON" "$CSO_GITHUB/push_github_pr_comment.py"
          --api-url "$GITHUB_API_URL"
          --cafile "$GITHUB_CAFILE"
          "$GITHUB_REPOSITORY"
          "$PULL_REQUEST_ID"
          GH_TOKEN
