name: Codesonar GitHub Demo
on:
  push:
    branches-ignore: main
env:
  PROJECT_NAME: ${{ github.event.repository.name }}
jobs:
  analyze:
    runs-on:
      - Debian12
    env:
      CODESONAR: /opt/codesonar/codesonar/bin/codesonar
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASS: "${{ secrets.CSONAR_HUB_PASS }}"
      CSONAR_HUB_PWFILE: "codesonar.hub.pwfile"
      CSONAR_HUB_URL: "https://partnerdemo.codesonar.com"
    container:
      image: ghcr.io/rdaultongt/csonar_github:gnucompilers-codesonar7.4p0
      credentials:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}
    timeout-minutes: 360
    steps:
     - uses: actions/checkout@v3
     - name: Create Hub Credential File
       run: echo "$CSONAR_HUB_PASS" > "$CSONAR_HUB_PWFILE"
    # next line required so we can access the main branch - it wll be called remotes/origin/main
     - run: git config --global --add safe.directory /__w/CSONAR_GITHUB/CSONAR_GITHUB
    # get the set of source files changed for the branch pushed as env var FILELIST
    # tr needed to put all results from git diff onto one space separated line
     - run: echo $GITHUB_REF
     - run: git branch -a
     - run: git diff --name-only remotes/origin/main $GITHUB_REF | tr '\n' ' '
     - run: FILELIST='git diff --name-only remotes/origin/main $GITHUB_REF | tr '\n' " "'
     - run: echo FILELIST = $FILELIST
  #   - name: Compile and Analyze the Code changes only
  #     run: >
  #        "$CODESONAR" analyze
  #        -foreground
  #        -auth password
  #        -hubuser "$CSONAR_HUB_USER"
  #        -hubpwfile "$CSONAR_HUB_PWFILE"
  #        -project /ROB/"$PROJECT_NAME"
  #        "$PROJECT_NAME"
  #        "$CSONAR_HUB_URL"
  #        gcc -c -I. ${{ env.FILELIST }}
