name: Codesonar GitHub Demo
on:
  push:
env:
  PROJECT_NAME: ${{ github.event.repository.name }}
jobs:
  analyze:
    runs-on:
      - Debian12
    env:
      CODESONAR: /opt/codesonar/codesonar/bin/codesonar
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASS: "${{ secrets.CSONAR_HUB_PASS }}"
      CSONAR_HUB_PWFILE: "codesonar.hub.pwfile"
      CSONAR_HUB_URL: "https://partnerdemo.codesonar.com"
    container:
      image: ghcr.io/rdaultongt/csonar_github:gnucompilers-codesonar7.4p0
      credentials:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}
    timeout-minutes: 360
    steps:
     - uses: actions/checkout@v3
     - name: Create Hub Credential File
       run: echo "$CSONAR_HUB_PASS" > "$CSONAR_HUB_PWFILE"
     - run: echo "branch pushed ':' $GITHUB_REF"
     - run: git diff --name-only main RJD
     - name: Compile and Analyze the Code
       run: >
          "$CODESONAR" analyze
          -foreground
          -auth password
          -hubuser "$CSONAR_HUB_USER"
          -hubpwfile "$CSONAR_HUB_PWFILE"
          -project /ROB/"$PROJECT_NAME"
          "$PROJECT_NAME"
          "$CSONAR_HUB_URL"
          gcc -c -I. demo.cpp
