name: Codesonar GitHub Demo
on:
  push:
  # dont rerun the workflow for alterations to the workflow script
    branches-ignore: main
env:
  PROJECT_NAME: ${{ github.event.repository.name }}
jobs:
  analyze:
  # perm required to solve "Resource not accessible by integration" warning when trying to upload SARIF
    permissions: write-all
    runs-on:
      - Debian12
    env:
      CODESONAR: /opt/codesonar/codesonar/bin/codesonar
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASS: "${{ secrets.CSONAR_HUB_PASS }}"
      CSONAR_HUB_PWFILE: "codesonar.hub.pwfile"
      CSONAR_HUB_URL: "https://partnerdemo.codesonar.com"
      CSPYTHON: /opt/codesonar/codesonar/bin/cspython
    container:
      image: ghcr.io/rdaultongt/csonar_github:gnucompilers-codesonar7.4p0
      credentials:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}
    timeout-minutes: 360
    steps:
     - uses: actions/checkout@v3
     - name: Create Hub Credential File
       run: echo "$CSONAR_HUB_PASS" > "$CSONAR_HUB_PWFILE"
    # next line required so we can access the main branch - it wll be called remotes/origin/main
     - run: git config --global --add safe.directory /__w/CSONAR_GITHUB/CSONAR_GITHUB
    # get the set of source files changed for the branch pushed as env var FILELIST
    # tr needed to put all results from git diff onto one space separated line
    # - run: echo $GITHUB_REF
    # - run: git branch -a
    # - run: git diff --name-only remotes/origin/main $GITHUB_REF | tr '\n' ' '
     - run: echo "FILELIST=`git diff --name-only remotes/origin/main $GITHUB_REF | grep -v yml | tr '\n' ' ' `" >> $GITHUB_ENV
     - name: Compile and Analyze the Code changes only
       run: >
          "$CODESONAR" analyze
          -foreground
          -auth password
          -hubuser "$CSONAR_HUB_USER"
          -hubpwfile "$CSONAR_HUB_PWFILE"
          -project /ROB/"$PROJECT_NAME"
          "$PROJECT_NAME"
          "$CSONAR_HUB_URL"
          gcc -c -I. $FILELIST
     - name: Pull Analysis Results from CodeSonar Hub
       run: >
          "$CODESONAR" dump_warnings.py
          -o warnings.sarif
          --hub "$CSONAR_HUB_URL"
          -auth password
          -hubuser "$CSONAR_HUB_USER"
          -hubpwfile "$CSONAR_HUB_PWFILE"
          --project-file "$PROJECT_NAME"
          --sarif
          --src-root "$GITHUB_WORKSPACE"
          -t 7200
     - name: Cleanup Credential File
       run: shred -u "$CSONAR_HUB_PWFILE"
     - name: Push Analysis Results to GitHub
       uses: github/codeql-action/upload-sarif@v2
       with:
          sarif_file: warnings.sarif
    # - name: Push Summary Report
    #   if: ${{ github.event.pull_request }}
    #   run: >
    #      "$CSPYTHON" "$CSO_GITHUB/sarif_summary.py"
     #     warnings.sarif
    #      "$CSONAR_HUB_URL"
     #     "$PROJECT_NAME"
     #     | "$CSPYTHON" "$CSO_GITHUB/push_github_pr_comment.py"
     #     --api-url "$GITHUB_API_URL"
      #    --cafile "$GITHUB_CAFILE"
      #    "$GITHUB_REPOSITORY"
     #     "$PULL_REQUEST_ID"
     #     GITHUB_TOKEN
